modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="test"
version="1.0.0"
displayName="Test"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Francisco VItal, MCreator"

[[dependencies.test]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




